/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  admin: {
    Classes: () => import('#controllers/admin/classes_controller'),
    Subjects: () => import('#controllers/admin/subjects_controller'),
    Tags: () => import('#controllers/admin/tags_controller'),
    Topics: () => import('#controllers/admin/topics_controller'),
    Users: () => import('#controllers/admin/users_controller'),
  },
  auth: {
    Auth: () => import('#controllers/auth/auth_controller'),
  },
  teacher: {
    Questions: () => import('#controllers/teacher/questions_controller'),
    Attachments: () => import('#controllers/teacher/attachments_controller'),
    Exams: () => import('#controllers/teacher/exams_controller'),
    ExamQuestions: () => import('#controllers/teacher/exam_questions_controller'),
    ExamClasses: () => import('#controllers/teacher/exam_classes_controller'),
    Attempts: () => import('#controllers/teacher/attempts_controller'),
  },
  shared: {
    Files: () => import('#controllers/shared/files_controller'),
  },
  student: {
    Exams: () => import('#controllers/student/exams_controller'),
    Attempts: () => import('#controllers/student/attempts_controller'),
  },
}
