/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class ClassStudentSchema extends BaseModel {
  static $columns = ['classId', 'enrolledAt', 'id', 'studentId'] as const
  $columns = ClassStudentSchema.$columns
  @column()
  declare classId: number
  @column.dateTime()
  declare enrolledAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare studentId: number
}

export class ClassSchema extends BaseModel {
  static $columns = ['academicYear', 'code', 'createdAt', 'createdBy', 'id', 'name', 'updatedAt'] as const
  $columns = ClassSchema.$columns
  @column()
  declare academicYear: string | null
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ExamAttemptAnswerSchema extends BaseModel {
  static $columns = ['answerPayload', 'answeredAt', 'examAttemptId', 'id', 'isCorrect', 'questionId', 'scoreAwarded'] as const
  $columns = ExamAttemptAnswerSchema.$columns
  @column()
  declare answerPayload: any
  @column.dateTime()
  declare answeredAt: DateTime
  @column()
  declare examAttemptId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isCorrect: boolean | null
  @column()
  declare questionId: number
  @column()
  declare scoreAwarded: string | null
}

export class ExamAttemptSchema extends BaseModel {
  static $columns = ['createdAt', 'deadlineAt', 'examClassId', 'examVariantId', 'id', 'isFlagged', 'score', 'startedAt', 'status', 'studentId', 'submittedAt', 'updatedAt', 'violationCount'] as const
  $columns = ExamAttemptSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deadlineAt: DateTime
  @column()
  declare examClassId: number
  @column()
  declare examVariantId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isFlagged: boolean
  @column()
  declare score: string | null
  @column.dateTime()
  declare startedAt: DateTime
  @column()
  declare status: string
  @column()
  declare studentId: number
  @column.dateTime()
  declare submittedAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare violationCount: number
}

export class ExamClassSchema extends BaseModel {
  static $columns = ['assignedBy', 'classId', 'closesAt', 'createdAt', 'examId', 'id', 'opensAt'] as const
  $columns = ExamClassSchema.$columns
  @column()
  declare assignedBy: number
  @column()
  declare classId: number
  @column.dateTime()
  declare closesAt: DateTime
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare examId: number
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare opensAt: DateTime
}

export class ExamQuestionSchema extends BaseModel {
  static $columns = ['examId', 'id', 'orderIndex', 'questionId', 'score'] as const
  $columns = ExamQuestionSchema.$columns
  @column()
  declare examId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orderIndex: number
  @column()
  declare questionId: number
  @column()
  declare score: string
}

export class ExamTagSchema extends BaseModel {
  static $columns = ['examId', 'id', 'tagId'] as const
  $columns = ExamTagSchema.$columns
  @column()
  declare examId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tagId: number
}

export class ExamVariantSchema extends BaseModel {
  static $columns = ['createdAt', 'examId', 'id', 'optionOrderMap', 'questionOrderMap', 'variantCode'] as const
  $columns = ExamVariantSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare examId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare optionOrderMap: any | null
  @column()
  declare questionOrderMap: any | null
  @column()
  declare variantCode: string
}

export class ExamSchema extends BaseModel {
  static $columns = ['createdAt', 'createdBy', 'description', 'durationMinutes', 'generationMode', 'id', 'maxViolationCount', 'shuffleOptions', 'shuffleQuestions', 'status', 'subjectId', 'title', 'totalScore', 'updatedAt'] as const
  $columns = ExamSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: number
  @column()
  declare description: string | null
  @column()
  declare durationMinutes: number
  @column()
  declare generationMode: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare maxViolationCount: number
  @column()
  declare shuffleOptions: boolean
  @column()
  declare shuffleQuestions: boolean
  @column()
  declare status: string
  @column()
  declare subjectId: number
  @column()
  declare title: string
  @column()
  declare totalScore: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class FileAttachmentSchema extends BaseModel {
  static $columns = ['createdAt', 'examId', 'fileName', 'id', 'mimeType', 'questionId', 'sizeBytes', 'storedPath', 'uploadedBy'] as const
  $columns = FileAttachmentSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare examId: number | null
  @column()
  declare fileName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare mimeType: string | null
  @column()
  declare questionId: number | null
  @column()
  declare sizeBytes: bigint | number | null
  @column()
  declare storedPath: string
  @column()
  declare uploadedBy: number
}

export class QuestionOptionSchema extends BaseModel {
  static $columns = ['content', 'id', 'isCorrect', 'label', 'orderIndex', 'questionId'] as const
  $columns = QuestionOptionSchema.$columns
  @column()
  declare content: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isCorrect: boolean
  @column()
  declare label: string
  @column()
  declare orderIndex: number
  @column()
  declare questionId: number
}

export class QuestionPartSchema extends BaseModel {
  static $columns = ['content', 'id', 'isCorrect', 'label', 'orderIndex', 'questionId'] as const
  $columns = QuestionPartSchema.$columns
  @column()
  declare content: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isCorrect: boolean
  @column()
  declare label: string
  @column()
  declare orderIndex: number
  @column()
  declare questionId: number
}

export class QuestionSchema extends BaseModel {
  static $columns = ['answerConfig', 'content', 'createdAt', 'createdBy', 'difficulty', 'explanation', 'id', 'isActive', 'questionType', 'subjectId', 'topicId', 'updatedAt'] as const
  $columns = QuestionSchema.$columns
  @column()
  declare answerConfig: any
  @column()
  declare content: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: number
  @column()
  declare difficulty: string
  @column()
  declare explanation: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare questionType: string
  @column()
  declare subjectId: number
  @column()
  declare topicId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RefreshTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'familyId', 'id', 'isRevoked', 'tokenHash', 'userId'] as const
  $columns = RefreshTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare familyId: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isRevoked: boolean
  @column()
  declare tokenHash: string
  @column()
  declare userId: number
}

export class SubjectSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'description', 'id', 'name', 'updatedAt'] as const
  $columns = SubjectSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TagSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'slug', 'updatedAt'] as const
  $columns = TagSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TeacherClassSchema extends BaseModel {
  static $columns = ['assignedAt', 'classId', 'id', 'teacherId'] as const
  $columns = TeacherClassSchema.$columns
  @column.dateTime()
  declare assignedAt: DateTime
  @column()
  declare classId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare teacherId: number
}

export class TopicSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'orderIndex', 'subjectId', 'updatedAt'] as const
  $columns = TopicSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare orderIndex: number
  @column()
  declare subjectId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'isActive', 'password', 'role', 'studentCode', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column()
  declare studentCode: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ViolationLogSchema extends BaseModel {
  static $columns = ['clientReportedAt', 'examAttemptId', 'id', 'metadata', 'occurredAt', 'violationType'] as const
  $columns = ViolationLogSchema.$columns
  @column.dateTime()
  declare clientReportedAt: DateTime | null
  @column()
  declare examAttemptId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare metadata: any | null
  @column.dateTime()
  declare occurredAt: DateTime
  @column()
  declare violationType: string
}
