/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type ClassTransformer from '#transformers/class_transformer'
import type ExamTransformer from '#transformers/exam_transformer'
import type QuestionTransformer from '#transformers/question_transformer'
import type SubjectTransformer from '#transformers/subject_transformer'
import type TagTransformer from '#transformers/tag_transformer'
import type TopicTransformer from '#transformers/topic_transformer'
import type UserTransformer from '#transformers/user_transformer'

export namespace Data {
  export type Class = InferData<ClassTransformer>
  export namespace Class {
    export type Variants = InferVariants<ClassTransformer>
  }
  export type Exam = InferData<ExamTransformer>
  export namespace Exam {
    export type Variants = InferVariants<ExamTransformer>
  }
  export type Question = InferData<QuestionTransformer>
  export namespace Question {
    export type Variants = InferVariants<QuestionTransformer>
  }
  export type Subject = InferData<SubjectTransformer>
  export namespace Subject {
    export type Variants = InferVariants<SubjectTransformer>
  }
  export type Tag = InferData<TagTransformer>
  export namespace Tag {
    export type Variants = InferVariants<TagTransformer>
  }
  export type Topic = InferData<TopicTransformer>
  export namespace Topic {
    export type Variants = InferVariants<TopicTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
}
